application: rockfsclient-dev
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest

handlers:

- url: /static
  static_dir: static

- url: /templates
  static_dir: templates
  application_readable: true
  login: admin

- url: /studentarea?/?.*
  script: authstudentarea.application
  login: required
  auth_fail_action: redirect

- url: /lessons?/?.*
  script: lessons-mockup.application

- url: /api?/?.*
  script: rockapi.application

- url: /test?/?.*
  script: testscript.application

- url: /
  script: devroot.application
