application: dotbiz-prod
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: latest

handlers:
- url: /static
  static_dir: static
  http_headers:
    Cache-Control: public
  secure: always
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always
- url: /favicon.ico
  static_files: static/image/favicon.ico
  upload: static/image/favicon.ico
  secure: always
- url: /templates
  static_dir: templates
  application_readable: true
  login: admin
  secure: always
- url: /dres/.* # GCSs
  script: gcs_wrapper.application
  secure: always
- url: /enableadmin # Hand-off
  script: login.application
  secure: always
- url: /modify/?.* # Non-Public
  script: modify.application
  login: admin
  secure: always
- url: /cron/.* # Non-Public
  script: cron.application
  login: admin
- url: /api/.* # Public 3rd-Party API Proxy
  script: api.application
  secure: always
- url: /sendmail/.* # Public 3rd-Party API Proxy
  script: sendmail.application
  secure: always
- url: /.* # Catch-all
  script: main.application
  secure: always

error_handlers:
  - error_code: over_quota
    file: gae-quota.html