application: dotbiz-prod
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: latest

pagespeed:
  domains_to_rewrite:
  - http://*.rocketeria.biz
  #url_blacklist:
  #- http://*.rocketeria.biz/dres/*
  enabled_rewriters:
  - InlineImages
  - MinifyCss
  disabled_rewriters:
  - InlineCss
  - ImageConvertToJpeg 

handlers:
- url: /static
  static_dir: static
  http_headers:
    Cache-Control: public
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /templates
  static_dir: templates
  application_readable: true
  login: admin
- url: /dres/.* # GCSs
  script: gcs_wrapper.application
- url: /enableadmin # Hand-off
  script: login.application
- url: /modify/?.* # Non-Public
  script: modify.application
  login: admin
- url: /cron/.* # Non-Public
  script: cron.application
  login: admin
- url: /api_proxy_pub/.* # Public 3rd-Party API Proxy
  script: api_proxy_pub.application
- url: /sendmail/.* # Public 3rd-Party API Proxy
  script: sendmail.application
- url: /.* # Catch-all
  script: main.application

error_handlers:
  - error_code: over_quota
    file: gae-quota.html