application: scms4gae
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest

handlers:

# Static non-application readable
- url: /static
  static_dir: static

- url: /templates
  static_dir: templates
  application_readable: true
  login: admin

# All GCS parent bins
- url: /res/.*
  script: gcs_wrapper.application

# Non-Public
- url: /modify/?.*
  script: modify.application
  login: admin

# Hand-off
- url: /enableadmin
  script: login.application

# Catch-all
- url: /.*
  script: main.application