application: dotbiz-dev
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: "latest"

pagespeed:
  domains_to_rewrite:
  - http://*.rocketeria.biz
  url_blacklist:
  - http://*.rocketeria.biz/dres
  enabled_rewriters:
  - InlineImages
  - MinifyCss
  disabled_rewriters:
  - InlineCss
  - ImageConvertToJpeg 
  - ImageResize 

handlers:
- url: /static
  static_dir: static
  http_headers:
    Cache-Control: public
- url: /templates
  static_dir: templates
  application_readable: true
  login: admin
# All GCS parent bins
- url: /dres/.*
  script: gcs_wrapper.application
# Hand-off
- url: /enableadmin
  script: login.application
# Non-Public
- url: /modify/?.*
  script: modify.application
  login: admin
- url: /cron/.*
  script: cron.application
  login: admin
# Public 3rd-Party API Proxy
- url: /api_proxy_pub/.*
  script: api_proxy_pub.application
# Catch-all
- url: /.*
  script: main.application

error_handlers:
  - error_code: over_quota
    file: gae-quota.html