application: dotbiz-dev
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: latest

handlers:

# Static non-application readable
- url: /static
  static_dir: static

- url: /templates
  static_dir: templates
  application_readable: true
  login: admin

# All GCS parent bins
- url: /dres/.*
  script: gcs_wrapper.application

# Hand-off
- url: /enableadmin
  script: login.application

# Non-Public
- url: /modify/?.*
  script: modify.application
  login: admin

- url: /cron/.*
  script: cron.application
  login: admin

# Public 3rd-Party API Proxy
- url: /api_proxy_pub/.*
  script: api_proxy_pub.application

# Catch-all
- url: /.*
  script: main.application