import webapp2
from google.appengine.api import mail
import get_env

def new():
	message = mail.EmailMessage(sender = "kyle@rocketeria.biz", to = "kyle@rocketeri.biz")
	return message

def templatify(message, site, namespace):
	version = get_env.version()
	universal_footer = '''

...
This message was generated by SCMS (the web server for rocketeria.biz).
Please do not reply. The robot cannot hear you scream.

If you believe this message was sent in error or contains an error, please forward it to kyle@rocketeria.biz. Include a brief explaination of the issue, and paste in the following information:

Environment: {site}
App Version: {version}
Script: sendmail.py
Namespace: sendmail.MailHandler().{namespace}
	'''

	message.sender = "SCMS Application Server <info@rocketeria.biz>"
	message.to = "info@rocketeria.biz"
	message.subject = "[SCMS] %s" % message.subject
	message.body = "%s\n%s" % (message.body, universal_footer)
	message.body = message.body.format(**locals())

	return message


class MailHandler(webapp2.RequestHandler):

	def post(self):

		uri = self.request.path.strip('/')
		message = message = mail.EmailMessage()


		if uri == "sendmail/deadlink":
			badurl = self.request.get("badurl")
			message.subject = "Missing resource reported by user"
			message.body = '''
A helpful user reported a missing page or file on rocketeria.biz. They were expecting to find something at:

{badurl}

...but got the 404 page instead.
			'''.format(**locals())

			site = get_env.from_url(badurl)

		message = templatify(message = message, site = site, namespace = "get() uri == \"sendmail\deadlink\"")
		message.send()


application = webapp2.WSGIApplication([
	(r'/sendmail/.*', MailHandler),
], debug=False)


